// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5zmGxow6yziotj8KPP-a4T5lFoDQNwN0',
    appId: '1:592475133016:web:ba437513b0bc88d6d1e62d',
    messagingSenderId: '592475133016',
    projectId: 'travel-diary-6a048',
    authDomain: 'travel-diary-6a048.firebaseapp.com',
    storageBucket: 'travel-diary-6a048.firebasestorage.app',
    measurementId: 'G-4PR6W90803',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgOb9BQZ9y8Dyap0UGpdP7APaJcXd3S1M',
    appId: '1:592475133016:android:ad5b429861dc4f8dd1e62d',
    messagingSenderId: '592475133016',
    projectId: 'travel-diary-6a048',
    storageBucket: 'travel-diary-6a048.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4qky3pgNdnv9yXSIa_jbyuwlB2aczvt0',
    appId: '1:592475133016:ios:c09917c5d978b530d1e62d',
    messagingSenderId: '592475133016',
    projectId: 'travel-diary-6a048',
    storageBucket: 'travel-diary-6a048.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4qky3pgNdnv9yXSIa_jbyuwlB2aczvt0',
    appId: '1:592475133016:ios:c09917c5d978b530d1e62d',
    messagingSenderId: '592475133016',
    projectId: 'travel-diary-6a048',
    storageBucket: 'travel-diary-6a048.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );
}
